REGIONS = (
    ('', ''),
    ('Blagoevgrad', 'Blagoevgrad'),
    ('Burgas', 'Burgas'),
    ('Varna', 'Varna'),
    ('Veliko Tarnovo', 'Veliko Tarnovo'),
    ('Vidin', 'Vidin'),
    ('Vratsa', 'Vratsa'),
    ('Gabrovo', 'Gabrovo'),
    ('Dobrich', 'Dobrich'),
    ('Kardzhali', 'Kardzhali'),
    ('Kyustendil', 'Kyustendil'),
    ('Lovech', 'Lovech'),
    ('Montana', 'Montana'),
    ('Pazardzhik', 'Pazardhik'),
    ('Pernik', 'Pernik'),
    ('Pleven', 'Pleven'),
    ('Plovdiv', 'Plovdiv'),
    ('Razgrad', 'Razgrad'),
    ('Ruse', 'Ruse'),
    ('Silistra', 'Silistra'),
    ('Sliven', 'Sliven'),
    ('Smolyan', 'Smolyan'),
    ('Sofiq City', 'Sofiq City'),
    ('Sofiq (province)', 'Sofiq (province)'),
    ('Stara Zagora', 'Stara Zagora'),
    ('Targovishte', 'Targovishte'),
    ('Haskovo', 'Haskovo'),
    ('Shumen', 'Shumen'),
    ('Yambol', 'Yambol')
)
