# Generated by Django 3.1.5 on 2021-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('Blagoevgrad', 'Blagoevgrad'), ('Burgas', 'Burgas'), ('Varna', 'Varna'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Vidin', 'Vidin'), ('Vratsa', 'Vratsa'), ('Gabrovo', 'Gabrovo'), ('Dobrich', 'Dobrich'), ('Kardzhali', 'Kardzhali'), ('Kyustendil', 'Kyustendil'), ('Lovech', 'Lovech'), ('Montana', 'Montana'), ('Pazardzhik', 'Pazardhik'), ('Pernik', 'Pernik'), ('Pleven', 'Pleven'), ('Plovdiv', 'Plovdiv'), ('Razgrad', 'Razgrad'), ('Ruse', 'Ruse'), ('Silistra', 'Silistra'), ('Sliven', 'Sliven'), ('Smolyan', 'Smolyan'), ('Sofiq City', 'Sofiq City'), ('Sofiq (province)', 'Sofiq (province)'), ('Stara Zagora', 'Stara Zagora'), ('Targovishte', 'Targovishte'), ('Haskovo', 'Haskovo'), ('Shumen', 'Shumen'), ('Yambol', 'Yambol')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
