# Generated by Django 3.1.5 on 2021-02-04 16:48

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210204_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), accounts.validators.contains_only_digits]),
        ),
    ]
