# Generated by Django 3.1.5 on 2021-01-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupe', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('where', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('horse_power', models.PositiveIntegerField()),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
    ]
