# Generated by Django 3.1.5 on 2021-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
