# Generated by Django 3.1.5 on 2021-01-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
