# Generated by Django 3.1.5 on 2021-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210125_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(default='', upload_to='cars'),
            preserve_default=False,
        ),
    ]
