# Generated by Django 3.1.5 on 2021-02-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210202_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='coupe',
        ),
        migrations.AddField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
