# Generated by Django 3.1.5 on 2021-02-04 16:48

import cars.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20210204_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2022), cars.validators.contains_only_digits]),
        ),
    ]
