# Generated by Django 3.1.5 on 2021-02-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20210204_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='images',
            new_name='image',
        ),
    ]
