# Generated by Django 3.1.5 on 2021-02-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210204_1848'),
        ('cars', '0016_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
